// AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY
// Source of truth: packages/widget-starter-template/template/
// This file is overwritten by scaffold/sync scripts. Edit the template instead.

/**
 * AppShell — React component wrappers for deployed and widget contexts.
 *
 * Extracted from main.tsx so that React Fast Refresh handles component
 * updates here WITHOUT re-executing main.tsx's mount side-effects.
 * This prevents Clerk's duplicate-provider guard from firing during HMR
 * (ClerkProvider uses a module-level counter that races when the entry
 * module re-evaluates and calls root.render() while Fast Refresh
 * simultaneously patches components).
 */

import { useEffect } from 'react'
import { useAuth, DeepSpacePill, GuestBanner, getWidgetAuthToken } from '@spaces/sdk/auth'
import { ProfileModalProvider } from '@spaces/sdk/profile'
import { AppSwitcherProvider } from '@spaces/sdk/app-switcher'
import { MobileHeader } from '@spaces/sdk/mobile'
import { initScreenshotListener } from '@spaces/sdk/screenshot'
import { getApiUrl } from '@spaces/sdk/config'
import { RecordProvider, RecordScope, MultiplexProvider, useUser, type UserProfile } from '@spaces/sdk/storage'
import { PlatformProvider } from '@spaces/sdk/platform'
import { getGlobalDOSchemas, USER_CONTENT_SCHEMAS, type SharedConnection } from '@spaces/sdk/worker'
import { schemas } from './schemas'
import { APP_ID, SCOPE_ID, SHARED_CONNECTIONS } from './constants'
import App from './App'

/**
 * Get the storage roomId for widgets.
 *
 * Canvas widgets receive their canvas roomId via URL search params
 * (injected by the parent canvas into the iframe src). This ensures
 * per-canvas data isolation — each canvas gets its own RecordRoom
 * Durable Object. Falls back to SCOPE_ID if no roomId param.
 */
function getWidgetRoomId(): string {
  const params = new URLSearchParams(window.location.search)
  return params.get('roomId') ?? SCOPE_ID
}

/**
 * Fetch user profile using postMessage auth (for canvas widgets).
 * Gets auth token from parent frame, then fetches /api/users/me.
 */
async function fetchUserViaPostMessage(): Promise<UserProfile> {
  const token = await getWidgetAuthToken()
  if (!token) {
    throw new Error('No auth token from parent')
  }

  const apiUrl = getApiUrl()
  const response = await fetch(`${apiUrl}/api/users/me`, {
    headers: { Authorization: `Bearer ${token}` },
  })

  if (!response.ok) {
    throw new Error(`Failed to fetch user: ${response.status}`)
  }

  return response.json()
}

/**
 * Canvas widget shell — Clerk is NOT in the tree, auth via postMessage.
 *
 * The parent canvas injects `roomId` as a URL search param on the iframe
 * src, so `getWidgetRoomId()` resolves it synchronously.
 */
export function WidgetShell() {
  useEffect(() => initScreenshotListener(), [])

  return (
    <RecordProvider
      roomId={getWidgetRoomId()}
      schemas={schemas}
      fetchUser={fetchUserViaPostMessage}
      allowAnonymous
    >
      <PlatformProvider>
        <App />
      </PlatformProvider>
    </RecordProvider>
  )
}

/**
 * Mounts sibling RecordScopes for each shared DO connection declared
 * in the app's SHARED_CONNECTIONS constant. Collection name resolution
 * via ScopeRegistry handles routing automatically — useQuery('transactions')
 * resolves to the ledger scope, useQuery('orders') to the app scope, etc.
 */
function SharedScopes({ children }: { children: React.ReactNode }) {
  const { user } = useUser()

  return (
    <>
      {(SHARED_CONNECTIONS as SharedConnection[]).map((conn) => {
        const roomId =
          conn.type === 'user'
            ? `user:${user?.id}`
            : `${conn.type}:${conn.instanceId}`
        // User-scope schemas are managed internally (rebuildUserSchemas in platform worker),
        // not in GLOBAL_DO_TYPES, so resolve them directly from the SDK.
        const doSchemas = conn.type === 'user' ? USER_CONTENT_SCHEMAS : getGlobalDOSchemas(conn.type)

        if (conn.type === 'user' && !user?.id) return null
        if (!doSchemas.length) return null

        return (
          <RecordScope
            key={roomId}
            roomId={roomId}
            schemas={doSchemas}
            appId={conn.type}
          />
        )
      })}
      {children}
    </>
  )
}

/**
 * Deployed / standalone shell — Clerk is in the tree, full auth flow.
 */
export function DeployedShell() {
  const { isLoaded } = useAuth()

  if (!isLoaded) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-surface">
        <div className="text-content-secondary">Authenticating...</div>
      </div>
    )
  }

  return (
    <ProfileModalProvider>
      <AppSwitcherProvider currentAppId={APP_ID}>
        <DeepSpacePill />
        <GuestBanner />
        <MobileHeader />
        <RecordProvider allowAnonymous>
          <MultiplexProvider appId={APP_ID}>
            <RecordScope roomId={SCOPE_ID} schemas={schemas} appId={APP_ID}>
              <SharedScopes>
                <PlatformProvider>
                  <App />
                </PlatformProvider>
              </SharedScopes>
            </RecordScope>
          </MultiplexProvider>
        </RecordProvider>
      </AppSwitcherProvider>
    </ProfileModalProvider>
  )
}
