// AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY
// Source of truth: packages/widget-starter-template/template/
// This file is overwritten by scaffold/sync scripts. Edit the template instead.

/**
 * ChatMount — Real implementation for deployed mini-apps with chat enabled.
 *
 * This file replaces the no-op stub from the widget template when the
 * deployment has chat enabled. It's rendered inside the existing
 * SpacesAuthProvider + PillCoordinatorProvider tree so it shares
 * the Clerk session and pill coordination context.
 *
 * Registers mobile chat actions with PillCoordinator so MobileHeader
 * can open/close chat on mobile without depending on @miyagi/chat.
 */

declare const __CHAT_DEV_MODE__: boolean | undefined

import { useEffect, useCallback } from 'react'
import { SpacesChatProvider, ChatDock, useTerminalStore } from '@spaces/sdk/chat'
import { usePillCoordinator } from '@spaces/sdk'

function MobileChatRegistrar(): null {
  const coordinator = usePillCoordinator()
  const setDockOpen = useTerminalStore(s => s.setDockOpen)
  const getDockOpen = useCallback(() => useTerminalStore.getState().dockOpen, [])

  // Extract the stable registerMobileChat function instead of depending on the
  // full coordinator object. The coordinator object reference changes whenever
  // mobileChat state changes in PillCoordinatorProvider, but registerMobileChat
  // is a stable useCallback. Depending on coordinator here creates an infinite
  // loop: effect calls registerMobileChat → mobileChat changes → context value
  // changes → coordinator changes → effect re-runs. This loop of high-priority
  // state updates starves React Router's startTransition navigation updates.
  const registerMobileChat = coordinator?.registerMobileChat

  useEffect(() => {
    if (!registerMobileChat) return
    return registerMobileChat({
      open: () => setDockOpen(true),
      close: () => setDockOpen(false),
      isOpen: getDockOpen,
    })
  }, [registerMobileChat, setDockOpen, getDockOpen])

  return null
}

const chatDevMode = typeof __CHAT_DEV_MODE__ !== 'undefined' ? __CHAT_DEV_MODE__ : undefined

export default function ChatMount() {
  return (
    <SpacesChatProvider developerMode={chatDevMode}>
      <ChatDock />
      <MobileChatRegistrar />
    </SpacesChatProvider>
  )
}
