// AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY
// Source of truth: packages/widget-starter-template/template/
// This file is overwritten by scaffold/sync scripts. Edit the template instead.

/**
 * Starter Template - Entry Point (mount only)
 *
 * This file MUST NOT define React components. Component definitions
 * cause @vitejs/plugin-react to treat it as a Fast Refresh boundary,
 * which re-executes the module body on every HMR update. That races
 * with Clerk's module-level duplicate-provider counter and crashes
 * with "multiple <ClerkProvider>" errors + removeChild DOM exceptions.
 *
 * All shell components live in AppShell.tsx where React Fast Refresh
 * can patch them in-place without re-running mount side-effects.
 */

import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import { SpacesAuthProvider, PillCoordinatorProvider, DeepSpaceThemeProvider, MobileBlockerProvider } from '@spaces/sdk'
import { isWidgetContext } from '@spaces/sdk/auth'
import { WidgetShell, DeployedShell } from './AppShell'
import ChatMount from './chat-mount'
import './styles.css'

const WIDGET_BASE = (window as any).__WIDGET_BASE__ ?? ''

const inWidget = isWidgetContext()

const tree = (
  <BrowserRouter basename={WIDGET_BASE}>
    <DeepSpaceThemeProvider>
      <MobileBlockerProvider>
        <PillCoordinatorProvider>
          {inWidget ? <WidgetShell /> : <DeployedShell />}
          <ChatMount />
        </PillCoordinatorProvider>
      </MobileBlockerProvider>
    </DeepSpaceThemeProvider>
  </BrowserRouter>
)

const container = document.getElementById('root')!
const root = (container as any).__root ?? createRoot(container)
;(container as any).__root = root

root.render(
  inWidget ? tree : <SpacesAuthProvider>{tree}</SpacesAuthProvider>,
)
