/**
 * Taskspace — "Momentum" design system (violet, dense, feature-forward)
 *
 * Shared inline-style tokens for the whole app. Values follow the
 * design handoff (direction 1b "Momentum"): Geist type, violet accent,
 * colorful status pills, hairline borders, calm 120–180ms transitions.
 */

/** Raw design tokens — import as `T` for one-off inline styles. */
export const T = {
  // Brand / accent
  accent: '#6B4CE6',
  accentStrong: '#4B2CC6',
  accentAvatar: '#7C5CFC',
  accentTint: '#F0ECFE',
  accentTint2: '#E4DBFB',
  accentGradient: 'linear-gradient(150deg,#8B6CFF,#6B4CE6)',
  progressGradient: 'linear-gradient(90deg,#8B6CFF,#6B4CE6)',

  // Neutrals
  bg: '#FFFFFF',
  bgSecondary: '#FAFAFC',
  bgTertiary: '#F8F8FB',
  bgSelected: '#FBFAFF',
  bgDetail: '#FBFBFC',
  textPrimary: '#1B1C2E',
  textSecondary: '#3A3C52',
  textMuted: '#6E7191',
  textFaint: '#9CA0B8',
  textFaintest: '#B8BCCC',
  border: '#ECEDF3',
  borderRow: '#F3F3F7',
  borderRowLight: '#F1F1F6',
  borderCard: '#E4E5EE',
  borderBtn: '#E7E7F0',
  borderTabs: '#EFEFF4',
  checkboxBorder: '#D6D3E8',

  // Status / priority
  green: '#22C08B',
  greenSoft: '#E4F7EF',
  orange: '#FF9F2E',
  orangeSoft: '#FFF3E0',
  red: '#FF4D4F',
  redSoft: '#FFEEEE',
  blue: '#4C6FFF',
  blueSoft: '#EAF0FF',
  purple: '#A855F7',
  purpleSoft: '#F6ECFE',
  gray: '#98A0B3',
  graySoft: '#F1F1F6',

  // Type
  font: "'Geist', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  mono: "'Geist Mono', ui-monospace, 'SF Mono', Menlo, monospace",

  // Shadows
  shadowCard: '0 1px 2px rgba(20,20,40,.04)',
  shadowCardRaised: '0 6px 16px -6px rgba(107,76,230,.28)',
  shadowBtnGlow: '0 2px 8px rgba(107,76,230,.3)',
  shadowHeroGlow: '0 8px 20px -6px rgba(107,76,230,.5)',
  shadowPanel: '0 1px 2px rgba(20,20,40,.04), 0 30px 60px -30px rgba(20,20,50,.22)',
  shadowModal: '0 30px 70px -20px rgba(20,18,50,.5)',
  scrim: 'rgba(20,18,40,.42)',

  // Motion
  transition: 'all 0.15s ease',
  transitionFast: 'all 0.12s ease',
} as const;

/** Mono uppercase label (sidebar sections, detail labels, column headers). */
export const monoLabel: React.CSSProperties = {
  fontFamily: T.mono,
  fontSize: '11px',
  fontWeight: 600,
  letterSpacing: '0.05em',
  textTransform: 'uppercase',
  color: T.textFaint,
};

export const styles: Record<string, React.CSSProperties> = {
  // ── Layout ────────────────────────────────────────
  container: {
    display: 'flex',
    height: 'calc(100vh - var(--mobile-header-height, 0px))',
    marginTop: 'var(--mobile-header-height, 0px)',
    fontFamily: T.font,
    color: T.textPrimary,
    backgroundColor: T.bg,
    overflow: 'hidden',
    fontSize: '13.5px',
    lineHeight: '1.5',
  },
  main: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    minWidth: 0,
  },
  contentWrapper: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
  },
  taskListArea: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    minWidth: 0,
  },

  // ── Loading ───────────────────────────────────────
  loading: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: 'calc(100vh - var(--mobile-header-height, 0px))',
    marginTop: 'var(--mobile-header-height, 0px)',
    gap: '12px',
    color: T.textFaint,
    fontFamily: T.font,
  },
  spinner: {
    width: 24,
    height: 24,
    border: `2px solid ${T.borderCard}`,
    borderTopColor: T.accent,
    borderRadius: '50%',
    animation: 'spin 0.6s linear infinite',
  },

  // ── Resize Handles ────────────────────────────────
  resizeHandle: {
    width: '6px',
    cursor: 'col-resize',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    zIndex: 10,
    position: 'relative',
  },
  resizeHandleLine: {
    width: '2px',
    height: '40px',
    borderRadius: '1px',
    backgroundColor: 'transparent',
    transition: 'background-color 0.15s ease',
  },
  resizeHandleLineActive: {
    backgroundColor: T.checkboxBorder,
  },
  detailResizeHandle: {
    width: '6px',
    cursor: 'col-resize',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    zIndex: 10,
    position: 'relative',
  },
  detailResizeHandleLine: {
    width: '2px',
    height: '40px',
    borderRadius: '1px',
    backgroundColor: 'transparent',
    transition: 'background-color 0.15s ease',
  },
  detailResizeHandleLineActive: {
    backgroundColor: T.checkboxBorder,
  },

  // ── Sidebar ───────────────────────────────────────
  sidebar: {
    backgroundColor: T.bgSecondary,
    borderRight: `1px solid ${T.border}`,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    flexShrink: 0,
  },
  sidebarHeader: {
    padding: '15px 16px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    borderBottom: `1px solid ${T.borderRowLight}`,
  },
  sidebarNav: {
    flex: 1,
    overflowY: 'auto',
    padding: '2px 10px 8px',
  },
  sidebarItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '7px 10px',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '13.5px',
    fontWeight: 500,
    color: T.textSecondary,
    transition: 'background-color 0.15s ease, color 0.15s ease',
    userSelect: 'none' as const,
    border: 'none',
    background: 'transparent',
    backgroundColor: 'transparent',
    outline: 'none',
    WebkitAppearance: 'none' as const,
    width: '100%',
    textAlign: 'left' as const,
  },
  sidebarItemActive: {
    backgroundColor: T.accentTint,
    color: T.accentStrong,
    fontWeight: 600,
  },
  sidebarItemHover: {
    backgroundColor: '#F1F1F6',
  },
  sidebarCount: {
    marginLeft: 'auto',
    fontFamily: T.mono,
    fontSize: '11px',
    color: T.textFaint,
    fontWeight: 500,
    minWidth: '20px',
    textAlign: 'right',
  },
  sidebarCountActive: {
    color: '#8B6CE6',
    backgroundColor: T.accentTint2,
    padding: '1px 7px',
    borderRadius: '20px',
    minWidth: 0,
    textAlign: 'center',
  },
  sidebarSection: {
    marginTop: '18px',
  },
  sidebarSectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '4px 10px',
    fontFamily: T.mono,
    fontSize: '11px',
    fontWeight: 600,
    color: T.textFaint,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  sidebarAddBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: T.textFaint,
    padding: '2px',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sidebarFooter: {
    borderTop: `1px solid ${T.borderRowLight}`,
    padding: '12px 16px',
    flexShrink: 0,
  },
  sidebarSignInBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    width: '100%',
    padding: '9px 12px',
    borderRadius: '9px',
    border: 'none',
    backgroundColor: T.accent,
    color: '#fff',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'opacity 0.15s ease',
    boxShadow: T.shadowBtnGlow,
  },
  sidebarUserFooter: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    width: '100%',
  },
  sidebarUserAvatar: {
    width: 28,
    height: 28,
    borderRadius: '50%',
    backgroundColor: T.accentAvatar,
    color: '#fff',
    fontSize: 12,
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    overflow: 'hidden',
  },
  sidebarUserInfo: {
    flex: 1,
    minWidth: 0,
  },
  sidebarUserName: {
    fontSize: 13,
    fontWeight: 550,
    color: T.textPrimary,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  sidebarUserEmail: {
    fontSize: 11,
    color: T.textFaint,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  sidebarSignOutBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: T.textFaint,
    padding: '4px',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  projectItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '9px',
    padding: '6px 10px',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '13.5px',
    fontWeight: 500,
    color: T.textSecondary,
    userSelect: 'none',
    border: 'none',
    background: 'none',
    width: '100%',
    textAlign: 'left',
  },
  projectDot: {
    width: 9,
    height: 9,
    borderRadius: '3px',
    flexShrink: 0,
  },
  projectChildren: {
    paddingLeft: '16px',
  },
  userItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '9px',
    padding: '6px 10px',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '13.5px',
    fontWeight: 500,
    color: T.textSecondary,
    userSelect: 'none',
    border: 'none',
    background: 'none',
    width: '100%',
    textAlign: 'left',
  },
  userAvatar: {
    width: 22,
    height: 22,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '10px',
    fontWeight: 600,
    color: '#fff',
    flexShrink: 0,
  },

  // ── View Header ───────────────────────────────────
  viewHeader: {
    padding: '16px 24px 0',
  },
  viewTitle: {
    fontSize: '22px',
    fontWeight: 700,
    margin: 0,
    color: T.textPrimary,
    letterSpacing: '-0.02em',
  },
  viewSubtitle: {
    fontSize: '12.5px',
    color: T.textMuted,
    marginTop: '2px',
  },

  // ── Toolbar ───────────────────────────────────────
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    gap: '7px',
    padding: '12px 24px',
    borderBottom: `1px solid ${T.borderTabs}`,
    flexWrap: 'wrap',
  },
  toolbarBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    padding: '5px 10px',
    borderRadius: '8px',
    border: `1px solid ${T.borderBtn}`,
    background: '#fff',
    cursor: 'pointer',
    fontSize: '12.5px',
    fontWeight: 500,
    color: T.textSecondary,
    transition: 'all 0.15s ease',
    whiteSpace: 'nowrap',
  },
  toolbarBtnActive: {
    borderColor: '#E1D9FB',
    color: T.accent,
    backgroundColor: T.accentTint,
  },
  toolbarSearch: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '5px 10px',
    borderRadius: '8px',
    border: `1px solid ${T.borderBtn}`,
    background: '#fff',
    flex: 1,
    maxWidth: '240px',
    marginLeft: 'auto',
  },
  toolbarSearchInput: {
    border: 'none',
    outline: 'none',
    fontSize: '12.5px',
    color: T.textPrimary,
    background: 'transparent',
    width: '100%',
    fontFamily: T.font,
  },

  // ── Primary button (New task) ─────────────────────
  primaryBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '6px 13px',
    borderRadius: '8px',
    border: 'none',
    background: T.accent,
    color: '#fff',
    cursor: 'pointer',
    fontSize: '12.5px',
    fontWeight: 600,
    transition: 'all 0.15s ease',
    whiteSpace: 'nowrap',
    boxShadow: T.shadowBtnGlow,
  },

  // ── View tabs (List / Board) ──────────────────────
  viewTabs: {
    display: 'flex',
    alignItems: 'center',
    gap: '18px',
    padding: '0 24px',
    borderBottom: `1px solid ${T.borderTabs}`,
  },
  viewTab: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '9px 2px',
    fontSize: '13px',
    fontWeight: 500,
    color: T.textMuted,
    cursor: 'pointer',
    border: 'none',
    background: 'none',
    borderBottom: '2px solid transparent',
    marginBottom: '-1px',
    transition: 'color 0.15s ease, border-color 0.15s ease',
  },
  viewTabActive: {
    color: T.accent,
    fontWeight: 600,
    borderBottom: `2px solid ${T.accent}`,
  },

  // ── Count pills (header) ──────────────────────────
  countPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    fontSize: '11px',
    fontWeight: 600,
    padding: '2px 9px',
    borderRadius: '20px',
    backgroundColor: T.graySoft,
    color: T.textMuted,
  },
  countPillGreen: {
    backgroundColor: T.greenSoft,
    color: T.green,
  },

  // ── Dropdown ──────────────────────────────────────
  dropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    marginTop: '4px',
    backgroundColor: '#fff',
    borderRadius: '10px',
    boxShadow: '0 6px 24px -4px rgba(20,20,50,0.14)',
    border: `1px solid ${T.borderCard}`,
    padding: '4px',
    zIndex: 1000,
    minWidth: '180px',
    maxHeight: '300px',
    overflowY: 'auto',
  },
  dropdownItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 10px',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 500,
    color: T.textSecondary,
    border: 'none',
    background: 'none',
    width: '100%',
    textAlign: 'left',
    transition: 'background-color 0.1s ease',
  },
  dropdownItemActive: {
    backgroundColor: T.accentTint,
    color: T.accent,
  },
  dropdownDivider: {
    height: '1px',
    backgroundColor: T.borderRowLight,
    margin: '4px 0',
  },

  // ── Task List ─────────────────────────────────────
  taskList: {
    flex: 1,
    overflowY: 'auto',
    padding: '0 0 4px',
  },
  taskListEmpty: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: T.textFaint,
    fontSize: '13.5px',
    textAlign: 'center',
    whiteSpace: 'pre-line',
    padding: '40px 24px',
  },
  dateGroup: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '8px',
    padding: '16px 24px 6px',
    fontSize: '12.5px',
    fontWeight: 700,
    color: T.textPrimary,
  },

  // ── Task Item ─────────────────────────────────────
  taskItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '11px',
    padding: '9px 24px 9px 21px',
    cursor: 'pointer',
    borderBottom: `1px solid ${T.borderRow}`,
    borderLeft: '3px solid transparent',
    transition: 'background-color 0.12s ease',
    userSelect: 'none',
  },
  taskItemSelected: {
    backgroundColor: T.bgSelected,
    borderLeft: `3px solid ${T.accent}`,
  },
  taskItemDragging: {
    opacity: 0.5,
    backgroundColor: T.bgSelected,
  },
  taskItemDragOver: {
    borderTop: `2px solid ${T.accent}`,
  },
  taskItemCompleted: {
    opacity: 0.5,
  },
  taskCheckbox: {
    width: 17,
    height: 17,
    borderRadius: '50%',
    border: `1.5px solid ${T.checkboxBorder}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    flexShrink: 0,
    transition: 'all 0.15s ease',
  },
  taskCheckboxChecked: {
    backgroundColor: T.green,
    borderColor: T.green,
  },
  taskContent: {
    flex: 1,
    minWidth: 0,
  },
  taskTitle: {
    fontSize: '13.5px',
    fontWeight: 500,
    color: T.textPrimary,
    margin: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  taskTitleCompleted: {
    textDecoration: 'line-through',
    color: '#8A8D98',
  },
  taskMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginTop: '2px',
    fontSize: '12px',
    fontWeight: 500,
    color: T.textMuted,
    flexWrap: 'wrap',
  },
  taskMetaItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  taskPriority: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '10.5px',
    fontWeight: 600,
    padding: '2px 8px',
    borderRadius: '20px',
  },
  taskTag: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '10.5px',
    padding: '2px 8px',
    borderRadius: '5px',
    fontWeight: 600,
  },
  taskProject: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    fontWeight: 500,
    color: T.textMuted,
  },
  taskProjectDot: {
    width: 8,
    height: 8,
    borderRadius: '2.5px',
    flexShrink: 0,
  },
  taskAssignee: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '12px',
  },
  taskAssigneeAvatar: {
    width: 22,
    height: 22,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '9px',
    fontWeight: 600,
    color: '#fff',
    flexShrink: 0,
  },
  taskTrashActions: {
    display: 'flex',
    gap: '4px',
    marginLeft: 'auto',
    flexShrink: 0,
  },
  taskTrashBtn: {
    padding: '4px 9px',
    borderRadius: '7px',
    border: `1px solid ${T.borderBtn}`,
    background: '#fff',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 500,
    color: T.textSecondary,
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    transition: 'all 0.15s ease',
  },
  subprojectIndicator: {
    fontSize: '11px',
    color: T.textFaint,
    fontStyle: 'italic',
  },
  kanbanBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    fontSize: '10.5px',
    fontWeight: 600,
    padding: '2px 8px',
    borderRadius: '20px',
  },

  // ── Quick Add ─────────────────────────────────────
  quickAdd: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '10px 24px',
    borderTop: `1px solid ${T.borderRowLight}`,
    backgroundColor: T.bgSecondary,
  },
  quickAddInput: {
    flex: 1,
    border: 'none',
    outline: 'none',
    fontSize: '13.5px',
    color: T.textPrimary,
    background: 'transparent',
    padding: 0,
    fontFamily: T.font,
  },

  // ── Task Detail (right sidebar) ───────────────────
  taskDetail: {
    borderLeft: `1px solid ${T.border}`,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    backgroundColor: T.bgDetail,
    flexShrink: 0,
  },
  detailHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 18px',
    borderBottom: `1px solid ${T.borderRowLight}`,
  },
  detailClose: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: T.textFaint,
    padding: '4px',
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailBody: {
    flex: 1,
    overflowY: 'auto',
    padding: '20px 18px',
  },
  detailTitleInput: {
    width: '100%',
    border: 'none',
    outline: 'none',
    fontSize: '17px',
    fontWeight: 650,
    letterSpacing: '-0.01em',
    lineHeight: '1.35',
    color: T.textPrimary,
    background: 'transparent',
    marginBottom: '12px',
    padding: 0,
    fontFamily: T.font,
  },
  detailNotesInput: {
    width: '100%',
    border: 'none',
    outline: 'none',
    fontSize: '13.5px',
    color: T.textMuted,
    background: 'transparent',
    resize: 'vertical',
    minHeight: '80px',
    padding: '8px',
    borderRadius: '6px',
    marginBottom: '16px',
    lineHeight: '1.6',
    fontFamily: T.font,
  },
  detailSection: {
    marginBottom: '16px',
  },
  detailLabel: {
    fontFamily: T.mono,
    fontSize: '11px',
    fontWeight: 600,
    color: T.textFaint,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    marginBottom: '6px',
    display: 'block',
  },
  detailField: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 10px',
    borderRadius: '8px',
    border: `1px solid ${T.borderCard}`,
    backgroundColor: '#fff',
    cursor: 'pointer',
    fontSize: '13px',
    color: T.textPrimary,
  },
  detailFieldValue: {
    flex: 1,
    fontSize: '13px',
    fontWeight: 500,
    color: T.textPrimary,
  },
  detailDateInput: {
    border: 'none',
    outline: 'none',
    fontSize: '13px',
    color: T.textPrimary,
    background: 'transparent',
    cursor: 'pointer',
    width: '100%',
    fontFamily: T.font,
  },
  detailSelect: {
    border: `1px solid ${T.borderCard}`,
    outline: 'none',
    fontSize: '13px',
    color: T.textPrimary,
    background: '#fff',
    padding: '8px 10px',
    borderRadius: '8px',
    width: '100%',
    cursor: 'pointer',
    appearance: 'none',
    fontFamily: T.font,
  },
  detailTagList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    marginBottom: '8px',
  },
  detailTag: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    padding: '3px 9px',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  detailAddTag: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    padding: '3px 9px',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: 500,
    color: T.textFaint,
    border: `1px dashed ${T.checkboxBorder}`,
    cursor: 'pointer',
    background: 'none',
  },
  detailActions: {
    padding: '12px 16px',
    borderTop: `1px solid ${T.borderRowLight}`,
    display: 'flex',
    gap: '8px',
  },
  detailActionBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '6px 11px',
    borderRadius: '8px',
    border: `1px solid ${T.borderBtn}`,
    background: '#fff',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 500,
    color: T.textSecondary,
    transition: 'all 0.15s ease',
  },
  detailActionBtnDanger: {
    borderColor: '#FFD9D9',
    color: T.red,
  },

  // ── Bulk Action Bar ───────────────────────────────
  bulkBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 24px',
    backgroundColor: T.accent,
    color: '#fff',
    fontSize: '13px',
  },
  bulkBarCount: {
    fontWeight: 600,
    marginRight: '4px',
  },
  bulkBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '4px 9px',
    borderRadius: '7px',
    border: '1px solid rgba(255,255,255,0.3)',
    background: 'rgba(255,255,255,0.15)',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 500,
    color: '#fff',
    transition: 'all 0.15s ease',
  },
  bulkBtnDanger: {
    borderColor: 'rgba(255,77,79,0.5)',
    background: 'rgba(255,77,79,0.25)',
    color: '#FFD9D9',
  },
  bulkClearBtn: {
    marginLeft: 'auto',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: 'rgba(255,255,255,0.7)',
    fontSize: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },

  // ── Modals ────────────────────────────────────────
  modal: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: T.scrim,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: '18px',
    padding: '24px',
    width: '380px',
    maxWidth: '90vw',
    boxShadow: T.shadowModal,
    animation: 'modalFadeIn 0.18s ease',
    fontFamily: T.font,
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '16px',
  },
  modalTitle: {
    fontSize: '17px',
    fontWeight: 650,
    letterSpacing: '-0.01em',
    margin: 0,
    color: T.textPrimary,
  },
  modalSubtitle: {
    fontSize: '13px',
    color: T.textMuted,
    marginBottom: '12px',
    marginTop: '-8px',
  },
  modalClose: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: T.textFaint,
    padding: '4px',
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalInput: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '9px',
    border: `1px solid ${T.borderCard}`,
    fontSize: '13.5px',
    color: T.textPrimary,
    outline: 'none',
    marginBottom: '16px',
    boxSizing: 'border-box',
    fontFamily: T.font,
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '8px',
  },
  editModalActions: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  btnCancel: {
    padding: '8px 16px',
    borderRadius: '9px',
    border: `1px solid ${T.borderBtn}`,
    background: '#fff',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 500,
    color: T.textSecondary,
    fontFamily: T.font,
  },
  btnSave: {
    padding: '8px 16px',
    borderRadius: '9px',
    border: 'none',
    background: T.accent,
    cursor: 'pointer',
    fontSize: '13px',
    color: '#fff',
    fontWeight: 600,
    boxShadow: T.shadowBtnGlow,
    fontFamily: T.font,
  },
  btnDelete: {
    padding: '8px 16px',
    borderRadius: '9px',
    border: 'none',
    background: T.red,
    cursor: 'pointer',
    fontSize: '13px',
    color: '#fff',
    fontWeight: 600,
    fontFamily: T.font,
  },
  btnDeleteText: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 500,
    color: T.red,
    padding: '4px 0',
  },
  colorPickerSection: {
    marginBottom: '16px',
  },
  colorPickerLabel: {
    fontFamily: T.mono,
    fontSize: '11px',
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: T.textFaint,
    marginBottom: '8px',
    display: 'block',
  },
  colorPickerRow: {
    display: 'flex',
    gap: '6px',
    flexWrap: 'wrap',
  },
  colorOption: {
    width: 26,
    height: 26,
    borderRadius: '8px',
    border: '2px solid transparent',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    padding: 0,
  },
  colorOptionSelected: {
    border: `2px solid ${T.textPrimary}`,
    transform: 'scale(1.1)',
  },

  // ── Delete modal ──────────────────────────────────
  deleteModalBody: {
    textAlign: 'center',
    padding: '8px 0 16px',
  },
  deleteWarningIcon: {
    marginBottom: '12px',
  },
  deleteModalText: {
    fontSize: '14px',
    color: T.textPrimary,
    margin: '0 0 8px',
  },
  deleteModalWarning: {
    fontSize: '13px',
    color: T.red,
    margin: 0,
  },

  // ── User Management Modal ─────────────────────────
  userManagement: {
    maxHeight: '400px',
    overflowY: 'auto',
    marginBottom: '16px',
  },
  userListItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '8px 10px',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'background-color 0.1s ease',
  },
  userListAvatar: {
    width: 32,
    height: 32,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '13px',
    fontWeight: 600,
    color: '#fff',
    flexShrink: 0,
  },
  userListInfo: {
    flex: 1,
    minWidth: 0,
  },
  userListName: {
    fontSize: '13.5px',
    fontWeight: 550,
    color: T.textPrimary,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  userListEmail: {
    fontSize: '12px',
    color: T.textFaint,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  userListActions: {
    display: 'flex',
    gap: '4px',
    flexShrink: 0,
  },

  // ── User Identity (bottom-left) ───────────────────
  userIdentity: {
    position: 'fixed',
    bottom: '12px',
    left: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 12px',
    borderRadius: '20px',
    backgroundColor: 'rgba(27,28,46,0.05)',
    fontSize: '12px',
    color: T.textSecondary,
    zIndex: 100,
    cursor: 'pointer',
    border: 'none',
    transition: 'background-color 0.15s ease',
  },
  userIdentityAvatar: {
    width: 20,
    height: 20,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '9px',
    fontWeight: 600,
    color: '#fff',
    flexShrink: 0,
  },

  // ── Read-Only Banner ──────────────────────────────
  readOnlyBanner: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexWrap: 'wrap' as const,
    gap: '8px',
    padding: '8px 24px',
    backgroundColor: T.orangeSoft,
    borderBottom: '1px solid #FFE4BD',
    fontSize: '13px',
    color: '#9A5B00',
  },
  readOnlyBannerMessage: {
    flex: 1,
    minWidth: '120px',
    textAlign: 'left' as const,
  },
  readOnlyBannerSignIn: {
    border: '1px solid #E0A54E',
    background: '#fff',
    borderRadius: '7px',
    padding: '5px 14px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#9A5B00',
    cursor: 'pointer',
    flexShrink: 0,
  },
  readOnlyBannerClose: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#9A5B00',
    fontSize: '16px',
    marginLeft: '4px',
    padding: '0 4px',
    flexShrink: 0,
  },

  // ── Confirm Modal ─────────────────────────────────
  confirmModalBody: {
    padding: '8px 0 20px',
    fontSize: '13.5px',
    color: T.textPrimary,
    lineHeight: '1.5',
  },
  confirmModalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '8px',
  },

  // ── Custom Dropdown ───────────────────────────────
  customDropdown: {
    position: 'relative',
    display: 'inline-block',
  },
  customDropdownMenu: {
    position: 'absolute',
    top: '100%',
    left: 0,
    marginTop: '4px',
    backgroundColor: '#fff',
    borderRadius: '10px',
    boxShadow: '0 6px 24px -4px rgba(20,20,50,0.14)',
    border: `1px solid ${T.borderCard}`,
    padding: '4px',
    zIndex: 1000,
    minWidth: '160px',
    maxHeight: '240px',
    overflowY: 'auto',
  },
  customDropdownItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 10px',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 500,
    color: T.textSecondary,
    border: 'none',
    background: 'none',
    width: '100%',
    textAlign: 'left',
  },
};
