/**
 * Things-like Task Manager — Inline Styles
 * Ported from the previous widget implementation
 */

export const styles: Record<string, React.CSSProperties> = {
  // ── Layout ────────────────────────────────────────
  container: {
    display: 'flex',
    height: 'calc(100vh - var(--mobile-header-height, 0px))',
    marginTop: 'var(--mobile-header-height, 0px)',
    fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", "Helvetica Neue", Arial, sans-serif',
    color: '#1D1D1F',
    backgroundColor: '#ffffff',
    overflow: 'hidden',
    fontSize: '14px',
    lineHeight: '1.5',
  },
  main: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    minWidth: 0,
  },
  contentWrapper: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
  },
  taskListArea: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    minWidth: 0,
  },

  // ── Loading ───────────────────────────────────────
  loading: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: 'calc(100vh - var(--mobile-header-height, 0px))',
    marginTop: 'var(--mobile-header-height, 0px)',
    gap: '12px',
    color: '#8E8E93',
    fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", "Helvetica Neue", Arial, sans-serif',
  },
  spinner: {
    width: 24,
    height: 24,
    border: '2px solid #E5E5EA',
    borderTopColor: '#007AFF',
    borderRadius: '50%',
    animation: 'spin 0.6s linear infinite',
  },

  // ── Resize Handles ────────────────────────────────
  resizeHandle: {
    width: '6px',
    cursor: 'col-resize',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    zIndex: 10,
    position: 'relative',
  },
  resizeHandleLine: {
    width: '2px',
    height: '40px',
    borderRadius: '1px',
    backgroundColor: 'transparent',
    transition: 'background-color 0.15s ease',
  },
  resizeHandleLineActive: {
    backgroundColor: '#C7C7CC',
  },
  detailResizeHandle: {
    width: '6px',
    cursor: 'col-resize',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    zIndex: 10,
    position: 'relative',
  },
  detailResizeHandleLine: {
    width: '2px',
    height: '40px',
    borderRadius: '1px',
    backgroundColor: 'transparent',
    transition: 'background-color 0.15s ease',
  },
  detailResizeHandleLineActive: {
    backgroundColor: '#C7C7CC',
  },

  // ── Sidebar ───────────────────────────────────────
  sidebar: {
    backgroundColor: '#F5F5F7',
    borderRight: '1px solid #E5E5EA',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    flexShrink: 0,
  },
  sidebarHeader: {
    padding: '16px 16px 8px',
    fontSize: '11px',
    fontWeight: 600,
    color: '#8E8E93',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  sidebarNav: {
    flex: 1,
    overflowY: 'auto',
    padding: '0 8px 8px',
  },
  sidebarItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '7px 10px',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '13px',
    color: '#1D1D1F',
    transition: 'background-color 0.15s ease',
    userSelect: 'none' as const,
    border: 'none',
    background: 'transparent',
    backgroundColor: 'transparent',
    outline: 'none',
    WebkitAppearance: 'none' as const,
    width: '100%',
    textAlign: 'left' as const,
  },
  sidebarItemActive: {
    backgroundColor: '#007AFF',
    color: '#fff',
  },
  sidebarItemHover: {
    backgroundColor: '#E5E5EA',
  },
  sidebarCount: {
    marginLeft: 'auto',
    fontSize: '12px',
    color: '#8E8E93',
    fontWeight: 500,
    minWidth: '20px',
    textAlign: 'right',
  },
  sidebarCountActive: {
    color: 'rgba(255,255,255,0.7)',
  },
  sidebarSection: {
    marginTop: '16px',
  },
  sidebarSectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '4px 10px',
    fontSize: '11px',
    fontWeight: 600,
    color: '#8E8E93',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  sidebarAddBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#8E8E93',
    padding: '2px',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  projectItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 10px',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '13px',
    color: '#1D1D1F',
    userSelect: 'none',
    border: 'none',
    background: 'none',
    width: '100%',
    textAlign: 'left',
  },
  projectDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    flexShrink: 0,
  },
  projectChildren: {
    paddingLeft: '16px',
  },
  userItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 10px',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '13px',
    color: '#1D1D1F',
    userSelect: 'none',
    border: 'none',
    background: 'none',
    width: '100%',
    textAlign: 'left',
  },
  userAvatar: {
    width: 22,
    height: 22,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '10px',
    fontWeight: 600,
    color: '#fff',
    flexShrink: 0,
  },

  // ── View Header ───────────────────────────────────
  viewHeader: {
    padding: '20px 24px 8px',
    borderBottom: '1px solid #F2F2F7',
  },
  viewTitle: {
    fontSize: '24px',
    fontWeight: 700,
    margin: 0,
    color: '#1D1D1F',
    letterSpacing: '-0.3px',
  },
  viewSubtitle: {
    fontSize: '13px',
    color: '#8E8E93',
    marginTop: '2px',
  },

  // ── Toolbar ───────────────────────────────────────
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 24px',
    borderBottom: '1px solid #F2F2F7',
    flexWrap: 'wrap',
  },
  toolbarBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '4px 8px',
    borderRadius: '6px',
    border: '1px solid #E5E5EA',
    background: '#fff',
    cursor: 'pointer',
    fontSize: '12px',
    color: '#636366',
    transition: 'all 0.15s ease',
    whiteSpace: 'nowrap',
  },
  toolbarBtnActive: {
    borderColor: '#007AFF',
    color: '#007AFF',
    backgroundColor: '#F0F5FF',
  },
  toolbarSearch: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '4px 10px',
    borderRadius: '6px',
    border: '1px solid #E5E5EA',
    background: '#fff',
    flex: 1,
    maxWidth: '240px',
    marginLeft: 'auto',
  },
  toolbarSearchInput: {
    border: 'none',
    outline: 'none',
    fontSize: '12px',
    color: '#1D1D1F',
    background: 'transparent',
    width: '100%',
  },

  // ── Dropdown ──────────────────────────────────────
  dropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    marginTop: '4px',
    backgroundColor: '#fff',
    borderRadius: '10px',
    boxShadow: '0 4px 20px rgba(0,0,0,0.12)',
    border: '1px solid #E5E5EA',
    padding: '4px',
    zIndex: 1000,
    minWidth: '180px',
    maxHeight: '300px',
    overflowY: 'auto',
  },
  dropdownItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 10px',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '13px',
    color: '#1D1D1F',
    border: 'none',
    background: 'none',
    width: '100%',
    textAlign: 'left',
    transition: 'background-color 0.1s ease',
  },
  dropdownItemActive: {
    backgroundColor: '#F0F5FF',
    color: '#007AFF',
  },
  dropdownDivider: {
    height: '1px',
    backgroundColor: '#E5E5EA',
    margin: '4px 0',
  },

  // ── Task List ─────────────────────────────────────
  taskList: {
    flex: 1,
    overflowY: 'auto',
    padding: '4px 0',
  },
  taskListEmpty: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: '#8E8E93',
    fontSize: '14px',
    textAlign: 'center',
    whiteSpace: 'pre-line',
    padding: '40px 24px',
  },
  dateGroup: {
    padding: '12px 24px 4px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#8E8E93',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },

  // ── Task Item ─────────────────────────────────────
  taskItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
    padding: '8px 24px',
    cursor: 'pointer',
    borderBottom: '1px solid #F2F2F7',
    transition: 'background-color 0.1s ease',
    userSelect: 'none',
  },
  taskItemSelected: {
    backgroundColor: '#F0F5FF',
  },
  taskItemDragging: {
    opacity: 0.5,
    backgroundColor: '#F0F5FF',
  },
  taskItemDragOver: {
    borderTop: '2px solid #007AFF',
  },
  taskItemCompleted: {
    opacity: 0.6,
  },
  taskCheckbox: {
    width: 20,
    height: 20,
    borderRadius: '50%',
    border: '2px solid #C7C7CC',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    flexShrink: 0,
    marginTop: '2px',
    transition: 'all 0.15s ease',
  },
  taskCheckboxChecked: {
    backgroundColor: '#007AFF',
    borderColor: '#007AFF',
  },
  taskContent: {
    flex: 1,
    minWidth: 0,
  },
  taskTitle: {
    fontSize: '14px',
    color: '#1D1D1F',
    margin: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  taskTitleCompleted: {
    textDecoration: 'line-through',
    color: '#8E8E93',
  },
  taskMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginTop: '2px',
    fontSize: '12px',
    color: '#8E8E93',
    flexWrap: 'wrap',
  },
  taskMetaItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '3px',
  },
  taskPriority: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '3px',
    fontSize: '11px',
    fontWeight: 500,
    padding: '1px 6px',
    borderRadius: '4px',
  },
  taskTag: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '3px',
    fontSize: '11px',
    padding: '1px 6px',
    borderRadius: '4px',
    fontWeight: 500,
  },
  taskProject: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '12px',
    color: '#8E8E93',
  },
  taskProjectDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    flexShrink: 0,
  },
  taskAssignee: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '12px',
  },
  taskAssigneeAvatar: {
    width: 16,
    height: 16,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '8px',
    fontWeight: 600,
    color: '#fff',
    flexShrink: 0,
  },
  taskTrashActions: {
    display: 'flex',
    gap: '4px',
    marginLeft: 'auto',
    flexShrink: 0,
  },
  taskTrashBtn: {
    padding: '4px 8px',
    borderRadius: '6px',
    border: '1px solid #E5E5EA',
    background: '#fff',
    cursor: 'pointer',
    fontSize: '11px',
    color: '#636366',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    transition: 'all 0.15s ease',
  },
  subprojectIndicator: {
    fontSize: '11px',
    color: '#8E8E93',
    fontStyle: 'italic',
  },
  kanbanBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '3px',
    fontSize: '11px',
    fontWeight: 500,
    padding: '1px 6px',
    borderRadius: '4px',
  },

  // ── Quick Add ─────────────────────────────────────
  quickAdd: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '10px 24px',
    borderTop: '1px solid #F2F2F7',
    backgroundColor: '#FAFAFA',
  },
  quickAddInput: {
    flex: 1,
    border: 'none',
    outline: 'none',
    fontSize: '14px',
    color: '#1D1D1F',
    background: 'transparent',
    padding: 0,
  },

  // ── Task Detail (right sidebar) ───────────────────
  taskDetail: {
    borderLeft: '1px solid #E5E5EA',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    backgroundColor: '#FAFAFA',
    flexShrink: 0,
  },
  detailHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    borderBottom: '1px solid #E5E5EA',
  },
  detailClose: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#8E8E93',
    padding: '4px',
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailBody: {
    flex: 1,
    overflowY: 'auto',
    padding: '16px',
  },
  detailTitleInput: {
    width: '100%',
    border: 'none',
    outline: 'none',
    fontSize: '18px',
    fontWeight: 600,
    color: '#1D1D1F',
    background: 'transparent',
    marginBottom: '12px',
    padding: 0,
  },
  detailNotesInput: {
    width: '100%',
    border: 'none',
    outline: 'none',
    fontSize: '14px',
    color: '#1D1D1F',
    background: 'transparent',
    resize: 'vertical',
    minHeight: '80px',
    padding: '8px',
    borderRadius: '6px',
    marginBottom: '16px',
    lineHeight: '1.5',
  },
  detailSection: {
    marginBottom: '16px',
  },
  detailLabel: {
    fontSize: '11px',
    fontWeight: 600,
    color: '#8E8E93',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    marginBottom: '6px',
    display: 'block',
  },
  detailField: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 10px',
    borderRadius: '8px',
    border: '1px solid #E5E5EA',
    backgroundColor: '#fff',
    cursor: 'pointer',
    fontSize: '13px',
    color: '#1D1D1F',
  },
  detailFieldValue: {
    flex: 1,
    fontSize: '13px',
    color: '#1D1D1F',
  },
  detailDateInput: {
    border: 'none',
    outline: 'none',
    fontSize: '13px',
    color: '#1D1D1F',
    background: 'transparent',
    cursor: 'pointer',
    width: '100%',
  },
  detailSelect: {
    border: '1px solid #E5E5EA',
    outline: 'none',
    fontSize: '13px',
    color: '#1D1D1F',
    background: '#fff',
    padding: '8px 10px',
    borderRadius: '8px',
    width: '100%',
    cursor: 'pointer',
    appearance: 'none',
  },
  detailTagList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    marginBottom: '8px',
  },
  detailTag: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    padding: '3px 8px',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: 500,
    cursor: 'pointer',
  },
  detailAddTag: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    padding: '3px 8px',
    borderRadius: '6px',
    fontSize: '12px',
    color: '#8E8E93',
    border: '1px dashed #C7C7CC',
    cursor: 'pointer',
    background: 'none',
  },
  detailActions: {
    padding: '12px 16px',
    borderTop: '1px solid #E5E5EA',
    display: 'flex',
    gap: '8px',
  },
  detailActionBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '6px 10px',
    borderRadius: '6px',
    border: '1px solid #E5E5EA',
    background: '#fff',
    cursor: 'pointer',
    fontSize: '12px',
    color: '#636366',
    transition: 'all 0.15s ease',
  },
  detailActionBtnDanger: {
    borderColor: '#FFD4D1',
    color: '#FF3B30',
  },

  // ── Bulk Action Bar ───────────────────────────────
  bulkBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 24px',
    backgroundColor: '#007AFF',
    color: '#fff',
    fontSize: '13px',
  },
  bulkBarCount: {
    fontWeight: 600,
    marginRight: '4px',
  },
  bulkBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '4px 8px',
    borderRadius: '6px',
    border: '1px solid rgba(255,255,255,0.3)',
    background: 'rgba(255,255,255,0.15)',
    cursor: 'pointer',
    fontSize: '12px',
    color: '#fff',
    transition: 'all 0.15s ease',
  },
  bulkBtnDanger: {
    borderColor: 'rgba(255,59,48,0.5)',
    background: 'rgba(255,59,48,0.2)',
    color: '#FFCDD2',
  },
  bulkClearBtn: {
    marginLeft: 'auto',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: 'rgba(255,255,255,0.7)',
    fontSize: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },

  // ── Modals ────────────────────────────────────────
  modal: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: '14px',
    padding: '24px',
    width: '360px',
    maxWidth: '90vw',
    boxShadow: '0 20px 60px rgba(0,0,0,0.2)',
    animation: 'modalFadeIn 0.2s ease',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '16px',
  },
  modalTitle: {
    fontSize: '17px',
    fontWeight: 600,
    margin: 0,
    color: '#1D1D1F',
  },
  modalSubtitle: {
    fontSize: '13px',
    color: '#8E8E93',
    marginBottom: '12px',
    marginTop: '-8px',
  },
  modalClose: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#8E8E93',
    padding: '4px',
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalInput: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '8px',
    border: '1px solid #E5E5EA',
    fontSize: '14px',
    color: '#1D1D1F',
    outline: 'none',
    marginBottom: '16px',
    boxSizing: 'border-box',
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '8px',
  },
  editModalActions: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  btnCancel: {
    padding: '8px 16px',
    borderRadius: '8px',
    border: '1px solid #E5E5EA',
    background: '#fff',
    cursor: 'pointer',
    fontSize: '14px',
    color: '#636366',
  },
  btnSave: {
    padding: '8px 16px',
    borderRadius: '8px',
    border: 'none',
    background: '#007AFF',
    cursor: 'pointer',
    fontSize: '14px',
    color: '#fff',
    fontWeight: 500,
  },
  btnDelete: {
    padding: '8px 16px',
    borderRadius: '8px',
    border: 'none',
    background: '#FF3B30',
    cursor: 'pointer',
    fontSize: '14px',
    color: '#fff',
    fontWeight: 500,
  },
  btnDeleteText: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '14px',
    color: '#FF3B30',
    padding: '4px 0',
  },
  colorPickerSection: {
    marginBottom: '16px',
  },
  colorPickerLabel: {
    fontSize: '12px',
    fontWeight: 500,
    color: '#8E8E93',
    marginBottom: '8px',
    display: 'block',
  },
  colorPickerRow: {
    display: 'flex',
    gap: '6px',
    flexWrap: 'wrap',
  },
  colorOption: {
    width: 28,
    height: 28,
    borderRadius: '50%',
    border: '2px solid transparent',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    padding: 0,
  },
  colorOptionSelected: {
    border: '2px solid #1D1D1F',
    transform: 'scale(1.1)',
  },

  // ── Delete modal ──────────────────────────────────
  deleteModalBody: {
    textAlign: 'center',
    padding: '8px 0 16px',
  },
  deleteWarningIcon: {
    marginBottom: '12px',
  },
  deleteModalText: {
    fontSize: '15px',
    color: '#1D1D1F',
    margin: '0 0 8px',
  },
  deleteModalWarning: {
    fontSize: '13px',
    color: '#FF3B30',
    margin: 0,
  },

  // ── User Management Modal ─────────────────────────
  userManagement: {
    maxHeight: '400px',
    overflowY: 'auto',
    marginBottom: '16px',
  },
  userListItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '8px 10px',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'background-color 0.1s ease',
  },
  userListAvatar: {
    width: 32,
    height: 32,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '13px',
    fontWeight: 600,
    color: '#fff',
    flexShrink: 0,
  },
  userListInfo: {
    flex: 1,
    minWidth: 0,
  },
  userListName: {
    fontSize: '14px',
    fontWeight: 500,
    color: '#1D1D1F',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  userListEmail: {
    fontSize: '12px',
    color: '#8E8E93',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  userListActions: {
    display: 'flex',
    gap: '4px',
    flexShrink: 0,
  },

  // ── User Identity (bottom-left) ───────────────────
  userIdentity: {
    position: 'fixed',
    bottom: '12px',
    left: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 12px',
    borderRadius: '20px',
    backgroundColor: 'rgba(0,0,0,0.05)',
    fontSize: '12px',
    color: '#636366',
    zIndex: 100,
    cursor: 'pointer',
    border: 'none',
    transition: 'background-color 0.15s ease',
  },
  userIdentityAvatar: {
    width: 20,
    height: 20,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '9px',
    fontWeight: 600,
    color: '#fff',
    flexShrink: 0,
  },

  // ── Read-Only Banner ──────────────────────────────
  readOnlyBanner: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    padding: '8px 24px',
    backgroundColor: '#FFF3CD',
    borderBottom: '1px solid #FFE69C',
    fontSize: '13px',
    color: '#856404',
  },
  readOnlyBannerClose: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#856404',
    fontSize: '16px',
    marginLeft: '8px',
    padding: '0 4px',
  },

  // ── Confirm Modal ─────────────────────────────────
  confirmModalBody: {
    padding: '8px 0 20px',
    fontSize: '14px',
    color: '#1D1D1F',
    lineHeight: '1.5',
  },
  confirmModalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '8px',
  },

  // ── Custom Dropdown ───────────────────────────────
  customDropdown: {
    position: 'relative',
    display: 'inline-block',
  },
  customDropdownMenu: {
    position: 'absolute',
    top: '100%',
    left: 0,
    marginTop: '4px',
    backgroundColor: '#fff',
    borderRadius: '10px',
    boxShadow: '0 4px 20px rgba(0,0,0,0.12)',
    border: '1px solid #E5E5EA',
    padding: '4px',
    zIndex: 1000,
    minWidth: '160px',
    maxHeight: '240px',
    overflowY: 'auto',
  },
  customDropdownItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 10px',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '13px',
    color: '#1D1D1F',
    border: 'none',
    background: 'none',
    width: '100%',
    textAlign: 'left',
  },
};

